services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tasks?max_connections=150
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: on-failure
    networks:
      - dns

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - dns

networks:
  dns:
