services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - memcached
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tasks?max_connections=150
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MEMCACHED_CACHE_SERVERS: memcached:11211
      SPRING_RABBITMQ_USERNAME: rabbitmq
      SPRING_RABBITMQ_PASSWORD: rabbitmq
    restart: on-failure
    networks:
      - dns

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - dns

  memcached:
    image: memcached:bookworm
    container_name: memcached
    ports:
      - 11211:11211
    networks:
      - dns

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - dns

networks:
  dns:
